name = "english-reading-app"
main = "src/index.ts"
compatibility_date = "2024-12-01" # Updated to recent date

# This section is needed for local development with Vite
[dev]
ip = "127.0.0.1"
port = 8787

# Environment variables for production deployment
# These should be set in Cloudflare Workers dashboard:
# - GOOGLE_PRIVATE_KEY (encrypted environment variable)
# - GOOGLE_CLIENT_EMAIL (encrypted environment variable)
#
# For local development, these are loaded from .env file
[vars]
# Add any non-sensitive environment variables here if needed

# Bind the D1 Database for access within the Worker
[[d1_databases]]
binding = "DB" # This is how you'll access the DB in your code (c.env.DB)
database_name = "english-reading-db"
database_id = "47751633-5a4f-4d46-a103-1c35949f32af" # <-- PASTE YOUR ID HERE

# Bind the R2 Bucket for access within the Worker
[[r2_buckets]]
binding = "R2_BUCKET" # This is how you'll access R2 in your code (c.env.R2_BUCKET)
bucket_name = "english-reading-bucket"

# Allow the frontend to be served by the Worker in production
# [site]
# bucket = "../frontend/dist"